# Site wide configuration

title: Computer Vision Enthusiast 
description: "Christopher B. Choy's Personal Blog"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
# For github use the following
# url: /
# For local debugging
url:

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap

# paginate:    7
# paginate_path: "page:num"

# Site owner
owner:
  name: Christopher B. Choy
  web: chrischoy.org
  email: chrischoy208@gmail.com
  twitter: 
  bio: "Computer Vision Enthusiast"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: 
    ad-client: 
    ad-slot: 

disqus-shortname: chrischoy


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
